### ISSUE TITLE
pip packaging: add support for 64bit Python on Windows

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#377]
At this time [open3d-python](https://pypi.org/project/open3d-python/) does not include binaries compiled for 64bit Python on Window 10.

This feature request was first mentioned in #369.
#369 has been addressed and should be closed.

**Comment by syncle** [comment]
addressed in #406

**Comment by qm2k** [comment]
Thank you for your work, is this change already included in 0.3.0.0? I still see `ImportError: DLL load failed` on 64-bit Python 3. 32-bit Python 2.7 works fine.

**Comment by yxlao** [comment]
@qm2k for "ImportError: DLL load failed on 64-bit Python 3", which python 3 version is that? Currently we only have 2.7, 3.5 and 3.6 supported

**Comment by qm2k** [comment]
Python 3.7 indeed. Is there some trick to make Open3D work with 3.7, or would you recommend downgrading to 3.6 for now?

**Comment by yxlao** [comment]
Compiling from source should work: http://www.open3d.org/docs/getting_started.html#windows. You'll need to specify `PYTHON_EXECUTABLE` to point to the python 3.7 executable in the cmake flags, e.g.
```
-DPYTHON_EXECUTABLE=C:\your-path-to-python3.7\python.exe 
```
Since there are a few request already to support python 3.7, we'll consider adding support for that in the next release.

**Comment by qm2k** [comment]
Thank you for your help!
